### ISSUE TITLE
Allow comments in whitelist

### ISSUE THREAD

**Issue by mpchadwick** [defactodesign/adminfirewall#3]
E.g.

```
# Client A home
XX.XX.XX.XX

# Company Office
XX.XX.XX.XX
```

etc...

**Comment by MikeParkin** [comment]
Hey @mpchadwick, 

This should already be allowed, because all we do is take the input of the field and explode it via newlines. The code will test if "# Client A home" is an ipaddress (which is a bit weird) but it won't have any adverse effect.

Cheers
Mike

**Comment by mpchadwick** [comment]
Ah nice. Closing this in that case.
